name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  datadog-api-key:
    description: 'Get from https://app.datadoghq.com/account/settings#api'
    required: true
  github-token:
    description: 'Set to secrets.GITHUB_TOKEN'
    required: true
  status:
    description: 'Set to job.status'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
