name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      if: always()
      with:
        datadog-api-key: ${{ secrets.DD_API_KEY }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        status: ${{ job.status }}
